## Import libraries and dataset

In [335]:
import pandas as pd
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)

In [336]:
path = './output.csv'

In [337]:
data = pd.read_csv(path)

###  Shape of the data

In [338]:
data.shape

(8184, 37)

### Features

In [339]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8184 entries, 0 to 8183
Data columns (total 37 columns):
LeasedFrom                 7901 non-null object
Engines                    8183 non-null object
CrashSiteElevation         8000 non-null object
Duration                   7930 non-null object
Narrative                  8130 non-null object
FlightNumber               8172 non-null object
Crew                       8184 non-null object
Location                   8184 non-null object
InvestigatingAgency        7930 non-null object
Type                       8182 non-null object
GroundCasualities          8097 non-null object
Status                     2590 non-null object
OnBehalfOf                 7950 non-null object
TotalFatalities            8184 non-null object
TotalAirFrameHrs           8165 non-null object
Nature                     8182 non-null object
AirplaneDamage             8184 non-null object
Released                   7930 non-null object
CarrierNumber              8184 non-null object
Phase                      8184 non-null object
Passengers                 8184 non-null object
OperatedBy                 7950 non-null object
DestinationAirport         8184 non-null object
OperatingFor               8144 non-null object
Date                       8184 non-null object
Time                       8172 non-null object
Cycles                     8082 non-null object
DownloadReport             7930 non-null object
DepartureAirport           8184 non-null object
Issued                     7930 non-null object
Number                     0 non-null float64
Registration               8184 non-null object
Operator                   8181 non-null object
DurationOfInvestigation    7432 non-null object
AirplaneFate               8172 non-null object
CollisionCasualties        8012 non-null object
FirstFlight                8184 non-null object
dtypes: float64(1), object(36)
memory usage: 2.3+ MB

In [340]:
print(len(data.columns))
data.columns

37

Index(['LeasedFrom', 'Engines', 'CrashSiteElevation', 'Duration', 'Narrative',
       'FlightNumber', 'Crew', 'Location', 'InvestigatingAgency', 'Type',
       'GroundCasualities', 'Status', 'OnBehalfOf', 'TotalFatalities',
       'TotalAirFrameHrs', 'Nature', 'AirplaneDamage', 'Released',
       'CarrierNumber', 'Phase', 'Passengers', 'OperatedBy',
       'DestinationAirport', 'OperatingFor', 'Date', 'Time', 'Cycles',
       'DownloadReport', 'DepartureAirport', 'Issued', 'Number',
       'Registration', 'Operator', 'DurationOfInvestigation', 'AirplaneFate',
       'CollisionCasualties', 'FirstFlight'],
      dtype='object')

### Examine Nulls and Data types

In [341]:
# Check the null values in the dataset
# Function to check the null counts in a dataframe
def checknullcount(df):
    info = []
    columns = ('Feature', 'Nullcount', 'Dtypes')
    for col in df.columns:
        nullcount = df[col].isnull().sum()
        datatype = df[col].dtypes
        info.append([col, nullcount, datatype])
    return (pd.DataFrame(columns=columns, data=info).sort_values('Nullcount', ascending = False))

(checknullcount(data))

                    Feature  Nullcount   Dtypes
30                   Number       8184  float64
11                   Status       5594   object
33  DurationOfInvestigation        752   object
0                LeasedFrom        283   object
17                 Released        254   object
29                   Issued        254   object
8       InvestigatingAgency        254   object
3                  Duration        254   object
27           DownloadReport        254   object
21               OperatedBy        234   object
12               OnBehalfOf        234   object
2        CrashSiteElevation        184   object
35      CollisionCasualties        172   object
26                   Cycles        102   object
10        GroundCasualities         87   object
4                 Narrative         54   object
23             OperatingFor         40   object
14         TotalAirFrameHrs         19   object
5              FlightNumber         12   object
34             AirplaneFate         12   object
25                     Time         12   object
32                 Operator          3   object
9                      Type          2   object
15                   Nature          2   object
1                   Engines          1   object
31             Registration          0   object
28         DepartureAirport          0   object
18            CarrierNumber          0   object
24                     Date          0   object
22       DestinationAirport          0   object
20               Passengers          0   object
19                    Phase          0   object
16           AirplaneDamage          0   object
13          TotalFatalities          0   object
7                  Location          0   object
6                      Crew          0   object
36              FirstFlight          0   object

## Check Feature Category - Aircraft and Airline Details

### LeasedFrom
- The company, organisation or individual that owns the aircraft, but did not operate it at the time of the accident. 
    - Null count - 283, datatype = object
        - Here I can assume that when the 'Leased From'value is null, the operator is using their own aircraft.
    - What do I i do?
        - Drop the column LeasedFrom

In [342]:
checkcols = ['OnBehalfOf', 'OperatedBy', 'OperatingFor', 'Operator', 'LeasedFrom']
cnt = []
null = []

for col in checkcols:
    row = []
    row.append(data[col].nunique())
    row.append(data[col].isnull().sum())
    row.append('a')
    data[col].fillna('-', inplace = True)
    null.append(row)
cols = ['Nunique','NullCount','x']
pd.DataFrame(columns=cols, data=null, index = checkcols)

              Nunique  NullCount  x
OnBehalfOf         10        234  a
OperatedBy          8        234  a
OperatingFor      183         40  a
Operator         2745          3  a
LeasedFrom         12        283  a

### OperatingFor
- The company, organisation or individual operating the aircraft at the time of the accident. This does not necessarily have to be the owner.

In [343]:
data['OperatingFor'].value_counts()

-                                                      7908
United Express                                           11
United Nations - UN                                      10
Saudi Arabian Airlines                                    8
FedEx Express                                             8
Delta Connection                                          7
American Eagle                                            7
Royal Australian Air Force - RAAF                         6
USAir Express                                             4
US Airways Express                                        4
Qantas Empire Airways                                     3
Sri Lanka Air Force                                       3
Manx2                                                     3
Air Force of the Democratic Republic of the Congo         3
Air Méditerranée                                          3
Baron Aviation                                            3
Platinum Jet Management                                   2
Regina Cargo Airlines                                     2
International Jet Charter                                 2
Agricultural High School                                  2
LAC - SkyCongo                                            2
Greenlandair                                              2
Alitalia                                                  2
Trigana Air Service                                       2
Continental Express                                       2
GEASA - Guinea Equatorial Airlines                        2
Aero-Tropics Air Services                                 2
Aviacsa                                                   2
Air New Zealand Link                                      2
Zaire International Cargo                                 2
Daallo Airlines                                           2
Japan Air Lines - JAL                                     2
Empire Airlines                                           2
Royal Air Force - RAF                                     2
Indian Airlines                                           2
Multinational Force and Observers - MFO                   2
African Air                                               2
International Red Cross                                   2
VIASA                                                     2
Kivu Air Services                                         2
Corporate Air                                             2
Chanchangi Airlines                                       2
Mountain Air Cargo                                        1
America West Express                                      1
Jazz Aviation                                             1
Air BAS Transportation                                    1
Flybe                                                     1
Regional Airlines                                         1
Interisland Airlines                                      1
Integerresources Inc. & Drayton Ass.                      1
Zimbabwe Express Airlines                                 1
Air New Zealand                                           1
Canadian Airways Congo                                    1
PENAS                                                     1
Cubana de Aviación                                        1
Anuschka Club International                               1
Maldivian Air Taxi                                        1
DHL Airways                                               1
Oil and Natural Gas Corporation - ONGC                    1
Federal Express                                           1
Kisangani Airlift                                         1
Kenting Aviation                                          1
Tarom                                                     1
Australian National Airways - ANA                         1
Royal Air Maroc - RAM                                     1
Linjeflyg                                                 1
Aer Arann                                                 1
Caribair, S.A.                                            1
Middle East Airlines - MEA                                1
American Eagle Airlines                                   1
Northwest Airlink                                         1
Sky Cabs                                                  1
ASKY Airlines                                             1
Gulf & Caribbean Cargo                                    1
AZZA Transport                                            1
Braathens SAFE                                            1
Occidental Petroleum                                      1
ECHO Flight                                               1
Air Canada Express                                        1
Trishan Air                                               1
Minerva Airlines                                          1
Smiths Aviation                                           1
Krasnoyarskaya Baza Lesoohrani                            1
Marsland Aviation                                         1
United States Army Air Force - USAAF                      1
US Airlines                                               1
Tadair                                                    1
All Nippon Airways - ANA                                  1
Servicios Aéreos Milenio                                  1
Cello Aviation                                            1
Avita Servicos Aéreos                                     1
Private Air Charters                                      1
South African Airways - SAA                               1
Comair                                                    1
Expo Aviation                                             1
Air America                                               1
Varig                                                     1
AKDON                                                     1
Piedmont Commuter                                         1
International Organization for Migration - IOM            1
Air Exec Services                                         1
Aerovias Guatemala                                        1
Guinee Air Service                                        1
Nigeria Airways                                           1
Transcontinental & Western Air - TWA                      1
Southern Right Air Charter                                1
West Air                                                  1
Ethiopian Airlines                                        1
Channel Express                                           1
Malaysian Airways                                         1
Freight Air                                               1
Türk Hava Yollari - THY                                   1
Katanga Express                                           1
Panarctic Oils                                            1
Dominican Services                                        1
LTE International Airways                                 1
Democratic Republic of the Congo Government               1
Carpatair                                                 1
Hoseba                                                    1
Southern Sudan Air Connection                             1
W. Jackson                                                1
Contact Air Flugdienst                                    1
Gryphon Airlines                                          1
Aspen Airways                                             1
Europe Aero Service - EAS                                 1
Uzbek Civil Aviation Adminstration                        1
Sirte Oil Company                                         1
Relief Air Transport                                      1
Angolan Government                                        1
American Air Transport                                    1
Volare Airlines                                           1
Alas Nacionales                                           1
Aerocosta Colombia                                        1
AmericanConnection                                        1
Lipetsk Aero Club                                         1
RusLine                                                   1
Caledonian Airways                                        1
Caribbean Atlantic Airlines                               1
Resort Airlines                                           1
Arizin Ventures, LLC                                      1
Air Nostrum                                               1
Mandated Airines Ltd. - MAL                               1
Trans Australia Airlines - TAA                            1
Kuwait Airways                                            1
LTU                                                       1
Seaboard & Western Airlines                               1
Prestige Tours                                            1
SOREM - Società Richerche Esperienze Meteorologiche       1
OMNI - Aviação e Tecnologia                               1
Wien Air Alaska                                           1
ROSTO Shahty                                              1
British Airways Express                                   1
M. Todd                                                   1
Aerocom                                                   1
Kasernierte Volkspolizei (KVP) Luft                       1
Robin Airlines                                            1
SISAM - Società Italiana Servizi Aerei Mediterranei       1
Faucett                                                   1
Iran Air                                                  1
Manunggal Air                                             1
THY Turkish Airlines                                      1
Trans-Asia                                                1
Sibaviatrans                                              1
Laredo Air                                                1
Eastern Air Lines                                         1
Air Arabia                                                1
Krasnoyarskie Avialinii                                   1
Azal Cargo                                                1
Libyan Arab Air Force                                     1
Air Norway                                                1
Linair                                                    1
Hughes Charter Air                                        1
DHL Aviation                                              1
Savanair (Angola)                                         1
Xieng Khouang Air Transport                               1
Icon Health and Fitness                                   1
Coco Aviation                                             1
National Iranian Oil Company - NIOC                       1
Taban Air                                                 1
Gading Sari Aviation Services                             1
National Airlines (National Air Cargo)                    1
Qantas                                                    1
Kam Air                                                   1
Name: OperatingFor, dtype: int64

### OnBehalfOf

In [344]:
data['OnBehalfOf'].value_counts()

-                                8173
U.S. Forest Service                 3
Cargo North                         1
Swiss International Air Lines       1
Continental Express                 1
US Department of State              1
Air France                          1
US Airways Express                  1
Northwest Airlink                   1
HOP!                                1
Name: OnBehalfOf, dtype: int64

### OperatedBy

In [345]:
data['OnBehalfOf'].value_counts()

-                                8173
U.S. Forest Service                 3
Cargo North                         1
Swiss International Air Lines       1
Continental Express                 1
US Department of State              1
Air France                          1
US Airways Express                  1
Northwest Airlink                   1
HOP!                                1
Name: OnBehalfOf, dtype: int64

### Operator

In [346]:
data['Operator'].value_counts()

United States Air Force - USAF                              462
-                                                           288
Royal Air Force - RAF                                       253
United States Navy                                          247
United States Army Air Force - USAAF                        221
Luftwaffe                                                    87
Air France                                                   62
Unknown                                                      49
Indian Air Force - IAF                                       47
Indian Airlines                                              46
Ejército del Aire                                            45
L'Armée de L'Air                                             42
Deutsche Lufthansa                                           40
Soviet Air Force                                             39
Eastern Air Lines                                            39
American Airlines                                            38
Aeroflot                                                     38
Aeroflot, Yakutsk Civil Aviation Directorate                 38
Avianca                                                      37
Imperial Airways                                             36
KLM Royal Dutch Airlines                                     34
Delta Air Lines                                              34
British Overseas Airways Corporation - BOAC                  31
Força Aérea Brasileira - FAB                                 29
Ethiopian Airlines                                           29
Royal Australian Air Force - RAAF                            28
private                                                      28
Royal Canadian Air Force - RCAF                              27
United Air Lines                                             27
Aeroflot / Ukraine                                           26
VASP - Viação Aérea São Paulo                                26
Merpati Nusantara Airlines                                   25
LOT Polskie Linie Lotnicze                                   24
CSA Ceskoslovenské Aerolinie                                 24
Philippine Air Lines                                         23
Fuerza Aérea Colombiana                                      23
Cubana de Aviación                                           23
Iran Air                                                     23
Türk Hava Kuvvetleri (Turkish Air Force)                     22
Iberia                                                       22
China National Aviation Corporation - CNAC                   22
Fuerza Aérea Argentina - FAA                                 21
Aeroflot, East Siberia Civil Aviation Directorate            21
Pakistan International Airlines - PIA                        21
Pan American World Airways (Pan Am)                          21
Garuda Indonesia Airways                                     20
Varig                                                        20
Saudi Arabian Airlines                                       19
United States Marine Corps                                   19
British European Airways - BEA                               19
Trans World Airlines - TWA                                   19
Aeroflot, Moscow Civil Aviation Directorate                  19
South African Air Force - SAAF                               19
Zakladu Uslug Agrolotniczych - ZUA                           18
Ala Littoria                                                 18
National Airlines                                            18
Transcontinental & Western Air - TWA                         17
Força Aérea Popular de Angola                                17
Aeroflot, Privolzhsk Civil Aviation Directorate              17
Royal Thai Air Force - RTAF                                  17
United Arab Airlines - UAA                                   16
Northwest Airlines                                           16
Aeroflot, North Kavkaz Civil Aviation Directorate            16
Aeroflot, Uralsk Civil Aviation Directorate                  16
Sabena                                                       16
United States Army                                           15
Türk Hava Yollari - THY                                      15
Scandinavian Airlines System - SAS                           15
Japan Maritime Self Defence Force - JMSDF                    15
Transporte Aéreo Militar - TAM                               15
Air Algérie                                                  15
Aeroflot, West Siberia Civil Aviation Directorate            15
Aeronautica Militare Italiana - AMI                          14
Marine Luchtvaart Dienst (MLD)                               14
Aéronavale                                                   14
Linea Aeropostal Venezolana - LAV                            14
Al Quwwat al-Jawwiya As-Sudaniya (Sudanese Air Force)        14
Fuerza Aérea del Peru - FAP                                  14
Lloyd Aéreo Boliviano - LAB                                  14
Aerolineas Argentinas                                        14
SATENA                                                       14
GUSMP, Directorate of Polar Aviation                         13
Cruzeiro do Sul                                              13
Middle East Airlines - MEA                                   13
Continental Air Lines                                        13
Pan American Airways (Pan Am)                                13
China Airlines                                               13
All Nippon Airways - ANA                                     13
Lineas Aéreas del Estado - LADE                              13
Air-India                                                    12
Pan American Grace Airways (Panagra)                         12
Air Union (France)                                           12
Royal Air Lao                                                12
Air America                                                  12
CAAC                                                         11
Russian Air Force                                            11
Tarom                                                        11
Aeroflot, Kazakstan Civil Aviation Directorate               11
Alitalia                                                     11
THY Turkish Airlines                                         11
Swissair                                                     11
Aeroflot / Uzbekistan                                        11
LAN Chile                                                    11
Panair do Brasil                                             10
Balkan Bulgarian Airlines                                    10
Faucett                                                      10
British Airways                                              10
South African Airways - SAA                                  10
Japan Air Lines - JAL                                        10
EgyptAir                                                      9
Aeroflot, Krasnoyarsk Civil Aviation Directorate              9
Capital Airlines                                              9
Alaska Airlines                                               9
Tentara Nasional Indonesia-AU (Air Force)                     9
Pelita Air Service                                            9
Polyarnaya Aviatsiya                                          9
TAAG Angola Airlines                                          9
TAME Ecuador                                                  9
Ariana Afghan Airlines                                        9
Sudan Airways                                                 9
Northwest Orient Airlines                                     9
Fuerza Aérea de Chile                                         9
Widerøes Flyveselskap                                         9
Aeroflot, Northern Civil Aviation Directorate                 9
United Airlines                                               9
Aeroflot, Far East Civil Aviation Directorate                 9
Air Canada                                                    9
Canadian Armed Forces                                         8
SAHSA - Servicio Aéreo de Honduras SA                         8
Transbrasil                                                   8
Lufthansa                                                     8
Aeroflot / Georgia                                            8
Líneas Aéreas de Nicaragua - LANICA                           8
Polish Air Force                                              8
Fuerza Aérea Revolucionaria                                   8
Pacific Western Airlines                                      8
Aviación del Ejército Ecuatoriana - AEE                       8
Kenn Borek Air                                                8
Dai Nippon Koku KK (Imperial Japanese Airways)                8
Aeroflot, Central Region Civil Aviation Directorate           8
TACA International Airlines                                   7
AVENSA                                                        7
Fuerza Aérea Mexicana                                         7
Imperial Iranian Air Force - IIAF                             7
Aeroflot, Magadan Civil Aviation Directorate                  7
Aeroflot, International Civil Aviation Directorate            7
Piedmont Airlines                                             7
Air National Guard                                            7
Dan-Air Services                                              7
Union of Burma Airways                                        7
Aviaco                                                        7
Democratic Republic of Afghanistan Air Force (DRAAF)          7
Mexicana de Aviación                                          7
Alco Aviation                                                 7
Paraense Transportes Aéreos                                   7
Dirgantara Air Services                                       7
Força Aérea Portuguesa                                        7
FedEx Express                                                 7
Fuerza Aérea Ecuatoriana                                      7
Bouraq Indonesia Airlines                                     7
Malev Hungarian Airlines                                      6
Belgische Luchtmacht                                          6
Aeroflot / Turkmenistan                                       6
Japan Air Self-Defense Force - JASDF                          6
Pacific Southwest Airlines - PSA                              6
Aeroflot, Tyumen Civil Aviation Directorate                   6
Malaysia Airlines                                             6
Hukbong Himpapawid ng Pilipinas (Philippine Air Force)        6
SGTA - Société Générale des Transports Aériens                6
Aviateca                                                      6
Continental Air Services, Inc. - CASI                         6
Kuwait Airways                                                6
Yemen Air Force                                               6
Air Cargo Carriers                                            6
Aeroflot / Azerbaijan                                         6
Jugoslovenski Aerotransport - JAT                             6
United States Army Air Corps - USAAC                          6
Aeroflot / Polar                                              6
Flying Tiger Line                                             6
Canadian Pacific Air Lines - CPAL                             6
Aeroflot / Belarus                                            6
Trigana Air Service                                           6
Southwest Airlines                                            6
DOSAAF                                                        6
VOTEC Servicios Aéreos Regionais                              6
Aigle Azur                                                    6
Handley Page Transport                                        6
Western Air Lines                                             6
Force Aérienne de la République Islamique de Mauritanie       6
Thai Airways                                                  6
ACES - Aerolineas Centrales de Colombia                       6
Armada Argentina, Comando de Aviación Naval                   6
Syndicato Condor                                              6
Talair                                                        6
Antonov Design Bureau                                         6
Trans-Canada Air Lines - TCAL                                 6
Air Zaire                                                     6
Trans Australia Airlines - TAA                                6
Canada Department of Transport                                6
Republic of China Air Force - ROCAF                           6
Iraqi Airways                                                 6
TransAsia Airways                                             6
Biman Bangladesh Airlines                                     6
MIAT - Mongolian Airlines                                     6
Singapore Airlines                                            5
Reeve Aleutian Airways                                        5
Lion Air                                                      5
Trans Maldivian Airways                                       5
Aeroflot / Tajikistan                                         5
Force Aérienne Tchadienne                                     5
Ethiopian Air Force                                           5
Aeroflot / Armenia                                            5
KNILM-Kon. Nederlandsch-Indische Luchtvaart Maatschappij      5
Mandala Airlines                                              5
Libyan Arab Air Force                                         5
Air Tanzania                                                  5
British Midland Airways - BMA                                 5
Royal Malaysian Air Force - RMAF                              5
Loganair                                                      5
Hewa Bora Airways                                             5
Compagnie Africaine d'Aviation - CAA                          5
Pilgrim Airlines                                              5
ATESA (Aerotaxis Ecuatorianos SA)                             5
Martinaire                                                    5
Beechcraft                                                    5
Línea Aérea Amaszonas                                         5
China Southern Airlines                                       5
Slick Airways                                                 5
American Airways                                              5
Braniff International Airways                                 5
Aeronica - Aerolineas Nicaraguenses                           5
Procuraduría General de la República (PGR)                    5
Eastern Provincial Airways                                    5
Elleniki Polemikí Aeroporía                                   5
Republic of Korea Air Force - ROKAF                           5
USAir                                                         5
Qantas                                                        5
Neptune Aviation Services                                     5
American Eagle Airlines                                       5
AREA Ecuador                                                  5
Far Eastern Air Transport - FEAT                              5
Air Libya                                                     5
Frigorifico Reyes                                             5
United Parcel Service - UPS                                   5
Bali International Air Service                                5
Crossair                                                      5
Bulgarian Air Force                                           5
Aer Lingus                                                    5
Nigeria Airways                                               5
British South American Airways - BSAA                         5
                                                           ...
Crown Charter Services                                        1
Black Sheep Aviation & Cattle Company                         1
TVA - Travel Air SA                                           1
Deutsche Versuchsanstalt für Luftfahrt (DVL)                  1
Kata Air Transport                                            1
British Gulf International Airlines                           1
AVCOM - Aviones Comerciales De Guatemala                      1
Redec Aviation                                                1
Evergreen International Aviation                              1
Avia Zov                                                      1
Telford Aviation                                              1
Lineas Aéreas de los Libertadores                             1
Consejo de Recursos Minerales                                 1
Downeast Airlines                                             1
Jim McGeorge                                                  1
O.K. Southwick                                                1
Automobil Club Argentino                                      1
Meteor Air Transport                                          1
Air Central                                                   1
Hudson Bay Air Transport                                      1
Petroproduccion - Unidad de Aviacion                          1
Enterprise General M.Forrest                                  1
Clayton V. Curtis                                             1
Aero Aysen                                                    1
Zapolyarye Airlines                                           1
Invicta Bearings (Pty) Ltd                                    1
FS Corsair Inc                                                1
Transavia Airlines                                            1
Malindi Air Services                                          1
Lady Lori (Kenya) Ltd                                         1
Business Air Connection                                       1
Civil Aeronautics Administration                              1
Northern Illinois Flight Center                               1
Transportes Aéreos de Timor                                   1
Simmons Airlines                                              1
The Connecticut National Bank                                 1
Batik Air                                                     1
Air Taxis Inc.                                                1
Evolga                                                        1
Ansett Airlines of Australia                                  1
Aeroflot / Moldova                                            1
N67AN Inc.                                                    1
Tatmadaw Lei (Myanmar Air Force)                              1
Transporturile Aeriene Romano-Sovietice - TARS                1
Kyrghyzstan Airlines                                          1
Skystream Airlines                                            1
Concord Airlines                                              1
Alsair                                                        1
Avcon Industries                                              1
Mass Bay Kustom Leasing                                       1
Desert Sand Aircraft Leasing                                  1
Excel-Jet                                                     1
Command Aviation                                              1
Airlines of New South Wales                                   1
Nature Air                                                    1
Gifford Aviation                                              1
Travel Service Airlines                                       1
Taxi Aero Centroamericano- TACSA                              1
Air Caribbean                                                 1
Blue Lines                                                    1
Colvin Aviation Inc.                                          1

### These 4 seem the same. Let me look at them to know the difference
    - LeasedFrom has 7888 empty values, 283 null values, [10 unique values]
        - There are 13 rows with valid Leased from values. In these 3 cases Operator is not provided.
    - OnBehalfOf has 7939 empty values, 234 null values [10 unique values]
        - There are only 11 valid values. I think I am going to drop this column
        - Mostly 
    - OperatedBy has 7943 empty values, 234 null values [8 unique values]
        - When operated By is filled, Operator is not provided. I will merge Operated By and Operator
    - OperatingFor has 7868 empty values, 40 null values [183 unique values]
        - When operating for is filled, Operator is not provided. I will merge Operated For and Operator
    - Operator has only 3 null values [ 2745 unique values]
        - Most are null here. I will drop all 3 null values

In [347]:
test = data[['OnBehalfOf', 'OperatedBy', 'OperatingFor', 'Operator', 'LeasedFrom','Date']]
test['OnBehalfOf'].fillna('-',inplace = True)
                          
test[(test['OnBehalfOf'] != '-') & (test['Operator'] != '-')]
# test['OnBehalfOf'].value_counts()

/Users/roshanlulu/anaconda3/lib/python3.6/site-packages/pandas/core/generic.py:3295: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(new_data)

,OnBehalfOf,OperatedBy,OperatingFor,Operator,LeasedFrom,Date
1527,U.S. Forest Service,-,-,Neptune Aviation Services,-,Saturday 26 June 2010
1891,U.S. Forest Service,-,-,Neptune Aviation Services,-,Sunday 3 June 2012
2238,U.S. Forest Service,-,-,Minden Air Corporation,-,Sunday 15 June 2014
4134,Air France,-,-,TAME Ecuador,-,Monday 20 April 1998

#### Operating For and Operator are never empty together. I will merge these 2 values into Operator, assuming it is the same.

In [348]:
# Merge 
operator = []
for index, op in enumerate(data['Operator']):
    if op == '-':
        op = data.ix[index, 'OperatingFor']
    else:
        pass
    operator.append(op)

data['Operator'] = operator
# After merging there are still 12 columns which dont have operator information
# 12 is a small number so I choose to remvoe these rows!
# data['Operator'] = [col.replace(' ', '_') for col in ufo.columns]
print(len(data))
data = data[data['Operator'] != '-']
len(data)

8184

8172

#### Drop the other columns - LeasedFrom,OnBehalfOf, OperatedBy

In [349]:
# Drop the columns
drop_col = ['LeasedFrom', 'OperatedBy', 'OperatingFor', 'OnBehalfOf']
data.drop(drop_col, axis = 1, inplace = True)

In [350]:
data.shape

(8172, 33)

In [351]:
# No of Unique Operators - 2857

data['Operator'].nunique()
# data['Operator'].value_counts()
# I amnot changing the operator names now. Once I get the country cleaned up, Then I can group the operators

2857

In [352]:
# There are a lot of names here. I want to categorize the airforce ones together for now
# Aim is to get something like Airforce
# Im nto grouping the other lines, since they can be used to subclassify within a coutnry classification
# Remove any text with numbers in it

data['Operator'] = ['Aeroflot' if 'Aeroflot' in t 
                    else 'Air Force' if 'Air Force' in t
#                     else 'US Air Force' if 'USAF' in t or 'USAAF' in t or 'United States Navy' in t
                else t for t in data['Operator']]
print(data['Operator'].nunique())
data['Operator'].value_counts()
 # Use regular expression to remove any text with numbers

2748

Air Force                                                   1359
Aeroflot                                                     360
United States Navy                                           247
Luftwaffe                                                     87
Air France                                                    62
Unknown                                                       49
Indian Airlines                                               48
Ejército del Aire                                             45
L'Armée de L'Air                                              42
Deutsche Lufthansa                                            40
Eastern Air Lines                                             40
American Airlines                                             38
Avianca                                                       37
Imperial Airways                                              36
Delta Air Lines                                               34
KLM Royal Dutch Airlines                                      34
British Overseas Airways Corporation - BOAC                   31
Ethiopian Airlines                                            30
Força Aérea Brasileira - FAB                                  29
private                                                       28
United Air Lines                                              27
Saudi Arabian Airlines                                        27
VASP - Viação Aérea São Paulo                                 26
Merpati Nusantara Airlines                                    25
LOT Polskie Linie Lotnicze                                    24
Iran Air                                                      24
CSA Ceskoslovenské Aerolinie                                  24
Cubana de Aviación                                            24
Fuerza Aérea Colombiana                                       23
Philippine Air Lines                                          23
China National Aviation Corporation - CNAC                    22
Iberia                                                        22
Pan American World Airways (Pan Am)                           21
Varig                                                         21
Pakistan International Airlines - PIA                         21
Fuerza Aérea Argentina - FAA                                  21
Garuda Indonesia Airways                                      20
Trans World Airlines - TWA                                    19
British European Airways - BEA                                19
United States Marine Corps                                    19
Ala Littoria                                                  18
Zakladu Uslug Agrolotniczych - ZUA                            18
National Airlines                                             18
Transcontinental & Western Air - TWA                          18
Força Aérea Popular de Angola                                 17
Sabena                                                        16
United Arab Airlines - UAA                                    16
Northwest Airlines                                            16
Türk Hava Yollari - THY                                       16
Scandinavian Airlines System - SAS                            15
Japan Maritime Self Defence Force - JMSDF                     15
Transporte Aéreo Militar - TAM                                15
Air Algérie                                                   15
FedEx Express                                                 15
United States Army                                            15
Marine Luchtvaart Dienst (MLD)                                14
Aéronavale                                                    14
Middle East Airlines - MEA                                    14
Aeronautica Militare Italiana - AMI                           14
All Nippon Airways - ANA                                      14
Aerolineas Argentinas                                         14
Fuerza Aérea del Peru - FAP                                   14
United Nations - UN                                           14
Lloyd Aéreo Boliviano - LAB                                   14
SATENA                                                        14
Linea Aeropostal Venezolana - LAV                             14
China Airlines                                                13
Air America                                                   13
Lineas Aéreas del Estado - LADE                               13
Alitalia                                                      13
GUSMP, Directorate of Polar Aviation                          13
Continental Air Lines                                         13
Pan American Airways (Pan Am)                                 13
Cruzeiro do Sul                                               13
THY Turkish Airlines                                          12
Tarom                                                         12
Pan American Grace Airways (Panagra)                          12
Air Union (France)                                            12
Japan Air Lines - JAL                                         12
Air-India                                                     12
Royal Air Lao                                                 12
South African Airways - SAA                                   11
Swissair                                                      11
Faucett                                                       11
United Express                                                11
LAN Chile                                                     11
CAAC                                                          11
Panair do Brasil                                              10
British Airways                                               10
Balkan Bulgarian Airlines                                     10
United Airlines                                                9
Sudan Airways                                                  9
Northwest Orient Airlines                                      9
Polyarnaya Aviatsiya                                           9
EgyptAir                                                       9
TAAG Angola Airlines                                           9
American Eagle                                                 9
TAME Ecuador                                                   9
Air Canada                                                     9
Alaska Airlines                                                9
Pelita Air Service                                             9
Widerøes Flyveselskap                                          9
Ariana Afghan Airlines                                         9
Fuerza Aérea de Chile                                          9
Capital Airlines                                               9
Líneas Aéreas de Nicaragua - LANICA                            8
Aviación del Ejército Ecuatoriana - AEE                        8
Pacific Western Airlines                                       8
Canadian Armed Forces                                          8
Trigana Air Service                                            8
Transbrasil                                                    8
Kenn Borek Air                                                 8
Fuerza Aérea Revolucionaria                                    8
Dai Nippon Koku KK (Imperial Japanese Airways)                 8
Lufthansa                                                      8
SAHSA - Servicio Aéreo de Honduras SA                          8
Aviaco                                                         7
Trans Australia Airlines - TAA                                 7
Fuerza Aérea Mexicana                                          7
Piedmont Airlines                                              7
Força Aérea Portuguesa                                         7
Air National Guard                                             7
Dirgantara Air Services                                        7
AVENSA                                                         7
Bouraq Indonesia Airlines                                      7
Union of Burma Airways                                         7
Paraense Transportes Aéreos                                    7
Fuerza Aérea Ecuatoriana                                       7
Mexicana de Aviación                                           7
Kuwait Airways                                                 7
Delta Connection                                               7
Dan-Air Services                                               7
TACA International Airlines                                    7
Alco Aviation                                                  7
DOSAAF                                                         6
Aigle Azur                                                     6
Qantas                                                         6
Japan Air Self-Defense Force - JASDF                           6
Pacific Southwest Airlines - PSA                               6
ACES - Aerolineas Centrales de Colombia                        6
Armada Argentina, Comando de Aviación Naval                    6
TransAsia Airways                                              6
Western Air Lines                                              6
Thai Airways                                                   6
Flying Tiger Line                                              6
Force Aérienne de la République Islamique de Mauritanie        6
Royal Air Maroc - RAM                                          6
Nigeria Airways                                                6
United States Army Air Corps - USAAC                           6
Trans-Canada Air Lines - TCAL                                  6
Belgische Luchtmacht                                           6
Canadian Pacific Air Lines - CPAL                              6
VOTEC Servicios Aéreos Regionais                               6
Jugoslovenski Aerotransport - JAT                              6
Air Zaire                                                      6
Iraqi Airways                                                  6
Syndicato Condor                                               6
Air Cargo Carriers                                             6
Canada Department of Transport                                 6
Aviateca                                                       6
SGTA - Société Générale des Transports Aériens                 6
Talair                                                         6
Antonov Design Bureau                                          6
MIAT - Mongolian Airlines                                      6
American Eagle Airlines                                        6
Handley Page Transport                                         6
Continental Air Services, Inc. - CASI                          6
Biman Bangladesh Airlines                                      6
Southwest Airlines                                             6
Malev Hungarian Airlines                                       6
Malaysia Airlines                                              6
Martinaire                                                     5
Beechcraft                                                     5
Alia Royal Jordanian Airlines                                  5
Aeronica - Aerolineas Nicaraguenses                            5
Frigorifico Reyes                                              5
British South American Airways - BSAA                          5
Channel Express                                                5
Crossair                                                       5
USAir                                                          5
Lion Air                                                       5
Maritime Central Airways                                       5
Force Aérienne Tchadienne                                      5
Mandala Airlines                                               5
Air Tanzania                                                   5
AREA Ecuador                                                   5
China Southern Airlines                                        5
Airfast Indonesia                                              5
British Midland Airways - BMA                                  5
Hewa Bora Airways                                              5
Reeve Aleutian Airways                                         5
Compagnie Africaine d'Aviation - CAA                           5
Slick Airways                                                  5
Procuraduría General de la República (PGR)                     5
Taiwan Airlines                                                5
United Parcel Service - UPS                                    5
Singapore Airlines                                             5
Australian National Airways - ANA                              5
Aer Lingus                                                     5
ATESA (Aerotaxis Ecuatorianos SA)                              5
Neptune Aviation Services                                      5
Elleniki Polemikí Aeroporía                                    5
Braniff International Airways                                  5
Bali International Air Service                                 5
Transafrik                                                     5
Trans Maldivian Airways                                        5
KNILM-Kon. Nederlandsch-Indische Luchtvaart Maatschappij       5
American Airways                                               5
Far Eastern Air Transport - FEAT                               5
Eastern Provincial Airways                                     5
Línea Aérea Amaszonas                                          5
Aeropesca Colombia                                             5
Pilgrim Airlines                                               5
Loganair                                                       5
Air Libya                                                      5
Khmer Hansa Airlines                                           4
Transportes Aéreos Peruanos - TAPSA                            4
Kalinga Airlines                                               4
Air New Zealand                                                4
China Eastern Airlines                                         4
Transportes Aéreos Litoral                                     4
Lynden Air Cargo                                               4
Autrex                                                         4
USAir Express                                                  4
British United Airways - BUA                                   4
US Airways                                                     4
Companhia Itaú de Transportes Aéreos                           4
Air Union                                                      4
Airworks                                                       4
Aeronaves de México                                            4
Libyan Arab Airlines                                           4
Aerotaca Colombia - Aerotransportes Casanare                   4
Intercontinental de Aviación                                   4
Union Aéromaritime de Transport                                4
Iraqi Government                                               4
Atlas Air                                                      4
Royal Nepal Airlines                                           4
SkyWest Airlines                                               4
Aerotal Colombia                                               4
REAL Transportes Aéreos                                        4
Aviación Naval Ecuatoriana - ANE                               4
Air Méditerranée                                               4
Uzbekistan Airways                                             4
Air Trek                                                       4
Líneas Aéreas del Caribe - LAC Colombia                        4
Manunggal Air                                                  4
AB Aerotransport                                               4
Austral Lineas Aéreas                                          4
DETA Moçambique Airlines                                       4
Transporte Aéreo Militar - TAM Peru                            4
                                                            ...
Kata Air Transport                                             1
British Gulf International Airlines                            1
AVCOM - Aviones Comerciales De Guatemala                       1
Redec Aviation                                                 1
Evergreen International Aviation                               1
Telford Aviation                                               1
Consejo de Recursos Minerales                                  1
Kyrghyzstan Airlines                                           1
Hudson Bay Air Transport                                       1
Invicta Bearings (Pty) Ltd                                     1
Zapolyarye Airlines                                            1
Aero Aysen                                                     1
Clayton V. Curtis                                              1
Enterprise General M.Forrest                                   1
Petroproduccion - Unidad de Aviacion                           1
Air Central                                                    1
Lady Lori (Kenya) Ltd                                          1
Meteor Air Transport                                           1
Automobil Club Argentino                                       1
O.K. Southwick                                                 1
Jim McGeorge                                                   1
Aeropanamericano                                               1
Lignum Ltd.                                                    1
Marsland Aviation                                              1
FS Corsair Inc                                                 1
Transavia Airlines                                             1
Downeast Airlines                                              1
Malindi Air Services                                           1
Business Air Connection                                        1
Civil Aeronautics Administration                               1
Northern Illinois Flight Center                                1
Transportes Aéreos de Timor                                    1
Simmons Airlines                                               1
The Connecticut National Bank                                  1
Batik Air                                                      1
Air Taxis Inc.                                                 1
Evolga                                                         1
Ansett Airlines of Australia                                   1
N67AN Inc.                                                     1
E. Marger                                                      1
Avia Zov                                                       1
TACA de Venezuela                                              1
MAP Arsenyev MSZ                                               1
Nature Air                                                     1
Colvin Aviation Inc.                                           1
Blue Lines                                                     1
Air Caribbean                                                  1
Taxi Aero Centroamericano- TACSA                               1
Gifford Aviation                                               1
Krasnoyarskaya Baza Lesoohrani                                 1
Airlines of New South Wales                                    1
Edwin L. Byrd                                                  1
Command Aviation                                               1
Excel-Jet                                                      1
Desert Sand Aircraft Leasing                                   1
Mass Bay Kustom Leasing                                        1

### Nature
- Nature of the flight. For passenger flights ‘domestic’  or ‘international’ is added where known. 
For a full list of flight natures used, see Appendix 3

In [365]:
data.reset_index(inplace = True)
### Now might be a good time to check the nature of the flight. If that is categorized well
data['Nature'].nunique()
## There are 25 unique nature of flights

## Can this be cleaned further?
data['Nature'].value_counts()

Military                             2181
Domestic Scheduled Passenger         1514
Unknown                               958
Cargo                                 825
International Scheduled Passenger     548
-                                     310
Domestic Non Scheduled Passenger      308
Ferry/positioning                     283
Training                              213
Executive                             212
Int'l Non Scheduled Passenger         147
Test                                  111
Passenger                              97
Agricultural                           71
Private                                68
Scheduled Passenger                    67
Illegal Flight                         59
Ambulance                              38
Survey/research                        37
Parachuting                            34
Fire fighting                          24
Non Scheduled Passenger                20
Official state flight                  19
Demonstration                          17
Aerial Work (Calibration, Photo)       11
Name: Nature, dtype: int64

In [354]:
# Id like to categorize them as follows into 3 categories.
# 0 - Others/Misc
# 1 - Passenger Flights
# 2 - Military
# Adding a new column for Flight_Nature_Code
code_list = []
for row in range(0, len(data)):
    code = 0
    nature = data.ix[row, 'Nature']
    if 'Military' in nature:
        code = 2
    elif 'Passenger' in nature:
        code = 1
    code_list.append(code)
data['Nature_Code'] = code_list

### Type
- Manufacturer and exact model involved in the accident. For Boeing models for instance a (first) customer code is being used. The second and third digits indicate this code. Customer code for Boeing 747-206 is '06', which is KLM. 
Where possible the name of the manufacturer is used at the time the airplane in question was built. For example, the MD-11 remains “McDonnell Douglas MD-11” and does not become Boeing MD-11 or Boeing (McDD) MD-11.



    - Ive reduced it into 27 categories of Type.
    - The ones with lesser no of incidents have been grouped together to form a category called Others

In [355]:
# import re
# # remove string with digits in it
# def cleanstring(text):
#     # split by word
#     # check if the word has a number
#     # delete word with number
#     text = re.sub("\S*\d\S*", "", text).strip()
#     t = text
#     if len(text) > 0:
#         t = text.split()
#         t = t[0]
#     return t

# data['Type'] = [cleanstring(t) for t in data['Type']]

In [356]:
data['Type'].value_counts()
# data['Type'].nunique()

# There are a lot of names here. I want to categorize it by removing the numbers first.
# Aim si to get something like Airbus, Douglas, Antonov, Boeing
# Remove any text with numbers in it

data['Type'] = ['Douglas' if 'Douglas' in t 
                else 'Antonov' if 'Antonov' in t
                else 'Cessna' if 'Cessna' in t
                else 'Airbus' if 'Airbus' in t
                else 'Boeing' if 'Boeing' in t
                else 'Bombardier' if 'Bombardier' in t
                else 'Embraer' if 'Embraer' in t
                else 'Curtiss' if 'Curtiss' in t
                else 'Catalina' if 'Catalina' in t
                else 'Learjet' if 'Learjet' in t
                else 'Fairchild' if 'Fairchild' in t
                else 'Lockheed' if 'Lockheed' in t
                else 'Beechcraft' if 'Beechcraft' in t
                else 'Britten-Norman' if 'Britten-Norman' in t
                else 'Jetstream' if 'Jetstream' in t
                else 'Ford' if 'Ford' in t
                else 'Yakovlev' if 'Yakovlev' in t
                else 'de Havilland' if 'de Havilland' in t
                else 'Sabreliner' if 'Sabreliner' in t
                else 'Lisunov' if 'Lisunov' in t
                else 'Tupolev' if 'Tupolev' in t
                else 'Junkers' if 'Junkers' in t
                else 'Vickers' if 'Vickers' in t
                else 'Fokker' if 'Fokker' in t
                else 'Swearingen' if 'Swearingen' in t
                else 'Ilyushin' if 'Ilyushin' in t
                else 'Others' for t in data['Type']]
print(data['Type'].nunique())
data['Type'].value_counts()
 # Use regular expression to remove any text with numbers

27

Douglas           1859
Others            1441
Antonov            635
Boeing             613
Lockheed           502
de Havilland       356
Curtiss            268
Cessna             268
Beechcraft         232
Junkers            228
Britten-Norman     183
Vickers            171
Fokker             152
Catalina           151
Ilyushin           145
Fairchild          139
Airbus             135
Learjet            127
Tupolev             99
Ford                98
Swearingen          81
Embraer             78
Lisunov             72
Yakovlev            57
Sabreliner          41
Jetstream           26
Bombardier          15
Name: Type, dtype: int64

In [357]:
## Id like to plot the Aircraft distributions wrt timelines
## See the dictibution of aircraft type to airline operator

In [358]:
# import re


# s = "ABCD abcd AB55 55CD A55D 5555"
# re.sub("\S*\d\S*", "", s).strip()

### FlightNumber - Verdict: Make it my unique ID.
- Flightnumber as assigned to the flight by the operator. They ar esupposed ot be unique values
- I am going to randomly assign unique values to it. I wont be retaining the original numbers. It will not make a difference to my data

In [364]:
# data[['CarrierNumber', 'FlightNumber']]
unique_id = [t for t in range(0, len(data))]
data['FlightNumber'] = unique_id

###  CarrierNumber  - Verdict: Drop it!

In [360]:
# I dont think carrier number is a useful feature.
# Im going to drop the column
data.drop('CarrierNumber', axis = 1, inplace = True)

### 37. FirstFlight - Is this the Year Built?

In [370]:
data['FirstFlight'].isnull().sum()
# No null values
data['FirstFlight'].value_counts()
# There are 2011 rows that have empty data
# Cleaning required
# sme have only year
# Some have the date of first flight and the age of the flight at that time
# Check the date of incident and check what we need for this field. 
# - Age mightbe a good field to get from here and the dat field

                                       2011
 1944                                   662
 1943                                   339
 1945                                   331
 1942                                   155
 1968                                   122
 1966                                   103
 1967                                    99
 1981                                    96
 1980                                    93
 1969                                    92
 1977                                    87
 1976                                    85
 1975                                    81
 1958                                    80
 1957                                    79
 1978                                    78
 1959                                    76
 1973                                    75
 1979                                    73
 1972                                    71
 1956                                    70
 1970                                    69
 1974                                    68
 1965                                    66
 1971                                    65
 1960                                    63
 1985                                    60
 1986                                    58
 1952                                    56
 1964                                    53
 1988                                    53
 1990                                    52
 1983                                    52
 1962                                    51
 1989                                    51
 1947                                    50
 1937                                    49
 1982                                    49
 1954                                    49
 1946                                    47
 1987                                    46
 1953                                    45
 1991                                    45
 1961                                    43
 1963                                    43
 1941                                    43
 1984                                    41
 1993                                    40
 1992                                    39
 1955                                    36
 1948                                    36
 1940                                    35
 1950                                    33
 1938                                    31
 2001                                    30
 1934                                    29
 1936                                    29
 1935                                    27
 1996                                    27
 1995                                    27
 1999                                    26
 2000                                    25
 2005                                    24
 1997                                    24
 1994                                    23
 1939                                    22
 1949                                    22
 1951                                    20
 2010                                    16
 2007                                    15
 1998                                    14
 2008                                    13
 2002                                    11
 1926                                    10
 1925                                    10
 2014                                     9
 2009                                     9
 2006                                     9
 2004                                     9
 1928                                     9
 2015                                     7
 1921                                     6
 2011                                     6
 1922                                     5
 1932                                     5
 2003                                     5
 1920                                     5
 1929                                     4
 1919                                     4
 1997-01-06  (16 years 3 months)          3
 2013                                     3
 1975-12-18  (4 years 1 months)           3
 2012                                     3
 1923                                     3
 1958-05-28  (40 years 11 months)         3
 1990-02-07  (27 years)                   3
 1946-07-27  (13 years 7 months)          2
 1958-05-11  (8 years 10 months)          2
 1928-10-26  (6 years 7 months)           2
 1973-11-21  (7 years 7 months)           2
 1988-09-05  (20 years 6 months)          2
 1987-02-11  (23 years )                  2
 1990-06-01  (13 years 9 months)          2
 1966-06-03  ()                           2
 1976-06-18  (7 years 10 months)          2
 1978-08-04  (8026 years 1 months)        2
 1962-03-02  (3 years )                   2
 1997-01-15  (17 years)                   2
 1962-05-09  (38 years)                   2
 1982-02-19  (16 years 3 months)          2
 1968-12-13  (46 years 2 months)          2
 1976-08-31  (32 years 8 months)          2
 1983-09-12  (24 years 7 months)          2
 1993-03-17  (2 years 10 months)          2
 1970-01-02  (8 years 3 months)           2
 1970-09-30  (15 years 4 months)          2
 1968-10-14  (8035 years 11 months)       2
 2007-12-20  (2 years 5 months)           2
 2002-02-14  (7 years 2 months)           2
 1929-06-27  (8 years 2 months)           2
 1996-06-03  (14 years 10 months)         2
 1988-07-07  (5 years 7 months)           2
 1970-04-24  (7 years 10 months)          2
 1985-11-05  (19 years 7 months)          2
 1988-03-17  (9 years 11 months)          2
 1996-05-02  (16 years 11 months)         2
 1950-10-19  (3 years 4 months)           2
 1997-01-06  (19 years 1 months)          2
 1968-11-19  (1 year 1 months)            2
 1930                                     2
 1988-02-10  (18 years )                  2
 1969-10-20  (6 months)                   2
 1963-05-08  (5 years 10 months)          2
 1975-04-29  (21 years 2 months)          2
 1933                                     2
 1985-07-03  (1 years)                    2
 1978-11-14  (27 years 5 months)          2
 1986-02-24  (10 months)                  2
 1929-02-26  (8 years 7 months)           2
 1987-12-08  (13 years 7 months)          2
 1990-03-16  (20 years 1 months)          2
 1988-11-23  (25 years 2 months)          2
 1991-11-12  (6 years 6 months)           2
 1970-08-26  (10 years 6 months)          2
 1987-09-01  (7 years 8 months)           2
 1927-08-22  (1 year 5 months)            2
 1980-05-06  (9 years 9 months)           2
 1932-03-31  (7 months)                   2
 1975-06-16  (3 years 11 months)          2
 1994-12-16  (2 months)                   2
 1967-10-09  (40 years 4 months)          2
 1958-02-13  (4 years 3 months)           2
 1977-03-07  (19 years 2 months)          2
 1967-07-28  (14 years 6 months)          2
 1995-05-11  (15 years 10 months)         2
 2014-03-28  (10 months)                  2
 1981-01-16  (27 years )                  2
 1982-03-16  (6 years 4 months)           2
 1979-01-08  (7 years 2 months)           1
 1976-05-26  (8 years )                   1
 1975-12-15  (8 years 6 months)           1
 1969-02-15  (12 years 11 months)         1
 1991-06-04  (20 years 11 months)         1
 1928-10-24  (24 years 7 months)          1
 1983-07-20  (28 years 10 months)         1
 1969-09-09  (29 years 9 months)          1
 1952-04-09  (1 year )                    1
 1980-05-29  (5 years 8 months)           1
 1988-09-14  (11 years 8 months)          1
 1992-06-09  (22 years 9 months)          1
 1982-04-16  (30 years 2 months)          1
 1962-10-04  (5 years 3 months)           1
 1992-11-10  (23 years 5 months)          1
 1949-06-21  (1 year 11 months)           1
 1929-01-27  (13 years 1 months)          1
 1984-04-12  (6 years 10 months)          1
 1985-10-11  (7 years 7 months)           1
 1975-06-17  (36 years 10 months)         1
 1968-02-28  (45 years 11 months)         1
 1998-08-24  (17 years 5 months)          1
 1988-12-21  (1 year 3 months)            1
 1928-10-12  (2 months)                   1
 1929-02-07  (2 years 6 months)           1
 1958-11-14  (15 years 4 months)          1
 1963-04-19  (17 years 9 months)          1
 1939-05-19  (22 years )                  1
 1986-01-30  (26 years 5 months)          1
 1973-11-20  (19 years 5 months)          1
 1984-12-21  (15 years 3 months)          1
 1962-08-02  (7 years 5 months)           1
 1974-04-12  (19 years 2 months)          1
 1962-03-09  (19 years )                  1
 1967-05-25  (10 months)                  1
 1985-11-05  (1 year 5 months)            1
 1976-04-13  (31 years 2 months)          1
 1986-07-03  (13 years 7 months)          1
 1970-05-08  (8 months)                   1
 1994-01-04  (20 years 1 months)          1
 1995-06-09  (3 years 10 months)          1
 1928-10-17  (6 years 6 months)           1
 1958-10-30  (23 years 5 months)          1
 1988-08-23  (6 years 5 months)           1
 1989-05-10  (4 years 9 months)           1
 1996-12-12  (9 years 5 months)           1
 1984-10-23  (16 years 4 months)          1
 1962-04-17  (10 months)                  1
 1995-04-23  (16 years 3 months)          1
 1990-04-05  (23 years )                  1
 1962-08-22  (22 years 7 months)          1
 1990-07-23  (7 years 7 months)           1
 1967-01-03  (3 years 2 months)           1
 1988-06-22  (26 years 8 months)          1
 1968-09-04  (5 months)                   1
 1997-05-09  (14 years 11 months)         1
 1928-05-01  (5 years 6 months)           1
 1958-06-11  (7 years 11 months)          1
 1946-06-15  (3 years 10 months)          1
 1990-06-01  (19 years )                  1
 2001-01-19  (15 years 4 months)          1
 1975-01-25  (24 years 5 months)          1
 1959-01-27  (11 years 2 months)          1
 1967-11-20  (34 years 3 months)          1
 1983-11-28  (10 years 4 months)          1
 1952-04-22  (1 year 9 months)            1
 1979-09-03  (3 years 5 months)           1
 1970-04-28  (15 years )                  1
 1987-10-08  (29 years 6 months)          1
 1980-01-22  (26 years 4 months)          1
 1929-01-31  (3 years 8 months)           1
 1970-09-10  (19 years 5 months)          1
 1974-11-26  (21 years 5 months)          1
 1989-12-19  (26 years 6 months)          1
 1960-01-14  (39 years )                  1
 1958-01-31  (9 years)                    1
 1984-12-07  (3 years 5 months)           1
 1997-03-23  (9 years 11 months)          1
 1959-05-29  (3 years 9 months)           1
 1957-02-01  (17 years )                  1
 1958-03-14  (1 year 11 months)           1
 1989-10-18  (23 years 8 months)          1
 1988-10-07  (24 years 7 months)          1
 1993-08-04  (9 years 7 months)           1
 1970-09-15  (5 years 8 months)           1
 1974-08-29  (11 years 7 months)          1
 2003-01-13  (14 years )                  1
 2002-01-24  (7 years 1 months)           1
 1967-03-06  (33 years)                   1
 1967-09-09  (1 year 4 months)            1
 1958-09-09  (4 years 6 months)           1
                                       ...
 2013-11-20  (2 years 7 months)           1
 1996-12-03  (20 years 4 months)          1
 1990-12-21  (21 years 2 months)          1
 1970-01-01  (20 years 2 months)          1
 1986-12-18  (1 year 1 months)            1
 1972-04-14  (18 years )                  1
 1957-12-30  (11 years 3 months)          1
 1980-06-12  (16 years 10 months)         1
 1960-06-01  (25 years 8 months)          1
 1963-09-19  (25 years 5 months)          1
 1988-02-10  (17 years)                   1
 1991-10-15  (15 years 4 months)          1
 1974-01-25  (7 years 5 months)           1
 1921-03-04  ()                           1
 1969-12-06  (2 years 2 months)           1
 2010-04-22  (6 years 11 months)          1
 1999-06-15  (9 years 7 months)           1
 1974-03-27  (22 years )                  1
 1928-08-30  (10 months)                  1
 2012-02-04  (1 year 4 months)            1
 1990-11-16  (21 years 7 months)          1
 1937-08-13  (4 years 7 months)           1
 1982-04-24  (24 years 2 months)          1
 1958-10-23  (5 years 7 months)           1
 1989-05-09  (18 years 10 months)         1
 1980-01-04  (25 years 1 months)          1
 2003-01-16  (10 years 4 months)          1
 1975-11-08  (27 years 4 months)          1
 1974-09-27  (24 years 4 months)          1
 1989-08-28  (3 years 7 months)           1
 1993-04-29  (21 years 2 months)          1
 1957-06-28  (16 years 7 months)          1
 1958-03-26  (2 years )                   1
 1958-04-30  (6 years 10 months)          1
 1958-07-29  (11 months)                  1
 2003-03-07  (13 years 5 months)          1
 1956-11-07  (4 months)                   1
 1975-10-26  (4 years 2 months)           1
 1929-05-01  (5 years 6 months)           1
 1977-07-20  (16 years 6 months)          1
 1949-06-30  (9 years 7 months)           1
 1967-02-13  (42 years 1 months)          1
 1934-06-17  (11 months)                  1
 1979-01-03  (19 years 4 months)          1
 1982-05-11  (8 years 10 months)          1
 1959-03-24  (23 years )                  1
 1967-10-24  (25 years 7 months)          1
 1991-03-21  (18 years 11 months)         1
 1967-08-27  (3 years 7 months)           1
 1984-04-11  (5 years 11 months)          1
 1987-05-11  (2 years 10 months)          1
 2007-12-11  (8 years 1 months)           1
 2014-10-30  (1 year 5 months)            1
 1976-05-18  (15 years 10 months)         1
 1992-09-10  (20 years 9 months)          1
 1994-04-25  (12 years 11 months)         1
 1992-12-21  (13 years 5 months)          1
 1928-07-24  (8 years )                   1
 1961-08-25  (3 years 4 months)           1
 1989-03-20  (16 years)                   1
 1977-07-13  (21 years 9 months)          1
 1998-11-20  (5 years 4 months)           1
 1956-03-14  (7 years 1 months)           1
 1951-08-08  (2 years 7 months)           1
 1958-04-13  (4 years 9 months)           1
 1970-07-16  (8 months)                   1
 1960-06-21  (8 years 7 months)           1
 1949-06-03  (2 years 8 months)           1
 1969-08-25  (19 years 9 months)          1
 1967-10-20  (20 years 7 months)          1
 1978-12-05  (3 years 3 months)           1
 1978-10-03  (22 years 5 months)          1
 1976-11-19  (6 years 5 months)           1
 1985-10-02  (13 years 6 months)          1
 2002-04-30  (13 years 1 months)          1
 1977-12-12  (12 years )                  1
 1981-02-16  (19 years)                   1
 1983-03-15  (15 years 10 months)         1
 1960-03-04  (33 years 11 months)         1
 1973-11-13  (21 years 2 months)          1
 1958-06-22  (4 years 10 months)          1
 1988-12-05  (9 years 7 months)           1
 1969-05-12  (16 years 9 months)          1
 1974-09-24  (7 years 8 months)           1
 1988-07-06  (21 years 7 months)          1
 2006-02-25  (7 years 4 months)           1
 1929-06-13  (9 years 2 months)           1
 1990-10-13  (24 years 5 months)          1
 1982-06-10  (2 years 9 months)           1
 1928-12-06  (5 months)                   1
 1969-10-07  (5 years 6 months)           1
 1977-08-19  (14 years 8 months)          1
 1981-09-04  (2 years 9 months)           1
 1969-04-02  (20 years )                  1
 1977-07-23  (4 years 11 months)          1
 1981-09-21  (2 years 5 months)           1
 1984-10-19  (10 years 5 months)          1
 1962-05-01  (11 years)                   1
 1974-09-18  (18 years 8 months)          1
 2007-05-03  (2 years )                   1
 1958-05-24  (4 years 11 months)          1
 1989-07-21  (6 years 9 months)           1
 1962-10-19  (2 years 7 months)           1
 1918-11-11  (9 months)                   1
 1969-09-25  (22 years 4 months)          1
 1928-05-10  (14 years)                   1
 2008-02-15  (4 months)                   1
 1966-11-19  (1 year 3 months)            1
 1990-05-04  (13 years 11 months)         1
 1929-06-25  (5 years)                    1
 1968-12-10  ()                           1
 1971-10-23  (26 years 5 months)          1
 2014-08-14  (2 years 8 months)           1
 1992-07-22  (20 years 7 months)          1
 1929-02-22  (13 years )                  1
 1986-11-25  (3 months)                   1
 1976-12-28  (14 years 2 months)          1
 1994-03-10  (19 years 4 months)          1
 2012-01-11  (2 years 1 months)           1
 1990-05-19  (3 years 11 months)          1
 1966-03-08  (22 years )                  1
 1978-08-03  (9 years 8 months)           1
 1968-08-28  (4 years 6 months)           1
 2010-07-20  (9 months)                   1
 2006-02-28  (5 years )                   1
 1979-07-02  (29 years 11 months)         1
 1998-07-31  (11 years 6 months)          1
 2009-08-06  (3 years 10 months)          1
 1958-09-01  (7 months)                   1
 1978-04-24  (29 years 9 months)          1
 1978-11-08  (1 year 5 months)            1
 1974-11-24  (19 years 5 months)          1
 1929-05-28  (8 months)                   1
 1977-05-31  (14 years 9 months)          1
 1982-04-01  (16 years )                  1
 1928-08-22  (2 years 3 months)           1
 2005-03-03  (7 years 3 months)           1
 1929-12-27  (7 months)                   1
 1997-03-07  (17 years 3 months)          1
 1970-09-09  (7 years 6 months)           1
 1966-06-09  (22 years 10 months)         1
 1985-08-21  (30 years 10 months)         1
 1973-05-02  (26 years 10 months)         1
 1982-08-11  (8 years 5 months)           1
 1981-12-11  (13 years 5 months)          1
 1969-07-16  (16 years 7 months)          1
 1996-06-11  (3 years 11 months)          1
 1984-03-01  (6 years 1 months)           1
 1975-11-11  (8 months)                   1
 1984-12-13  (27 years 5 months)          1
 1987-06-19  (28 years )                  1
 1984-12-04  (18 years 2 months)          1
 1988-10-06  (3 months)                   1
 1957-04-26  (5 years 11 months)          1
 1977-05-28  (11 years 10 months)         1
 1975-10-06  (9 years 4 months)           1
 1971-03-19  (8 years 2 months)           1
 1982-02-03  (15 years 11 months)         1
 1989-01-14  (9 years 2 months)           1
 1983-10-13  (16 years 4 months)          1
 1996-12-02  (18 years 1 months)          1
 1979-11-13  (33 years 3 months)          1
 1969-01-22  (32 years)                   1
 1929-09-13  (3 months)                   1
 1969-04-09  (15 years 10 months)         1
 1994-03-04  (8 years 10 months)          1
 1976-05-26  (26 years 8 months)          1
 1968-12-12  (16 years 6 months)          1
 1929-01-26  (4 years 4 months)           1
 1953-05-27  (9 years 9 months)           1
 1987-06-12  (7 years 10 months)          1
 1975-02-12  (3 years 2 months)           1
 1992-10-09  (11 years 3 months)          1
 1955-10-14  (17 years 6 months)          1
 1990-06-19  (22 years)                   1
 1989-04-04  (26 years 3 months)          1
 1992-09-02  (21 years 7 months)          1
 1959-11-19  (23 years 7 months)          1
 1965-01-21  (50 years 4 months)          1
 1989-01-11  (18 years)                   1
 2006-10-18  (8 years 6 months)           1
 2015-11-21  (1 year 4 months)            1
 1931-02-24  (5 years 6 months)           1
 1995-09-04  (5 months)                   1
 1971-09-14  (5 years 7 months)           1
 1963-10-09  (34 years 8 months)          1
 2005-03-15  (11 years 3 months)          1
 1929-02-28  (2 years 5 months)           1
 1978-09-08  (4 years 4 months)           1
 1991-11-14  (7 years 3 months)           1
 1929-08-10  (10 years 7 months)          1
 1972-09-27  (2 years 4 months)           1
 1965-03-11  (11 months)                  1
 1969-09-30  (26 years 8 months)          1
 2012-11-12  (1 year 3 months)            1
 1976-05-08  (6 years 11 months)          1
 1982-03-12  (2 years 10 months)          1
 2003-07-08  (12 years 9 months)          1
 1976-09-20  (19 years 8 months)          1
 1980-12-19  (28 years 2 months)          1
 1976-05-16  (10 years 8 months)          1
 1960-12-10  (28 years 2 months)          1
 1969-08-04  (5 months)                   1

### 32. Registration
- The registrationmark applied on the  the aircaft at the time of the accident. Airplanes involved in some occurrences carried illegal/unofficial registration marks. In these cases the unofficial registration is given.

### 31. Number
- Manufacturer serial number/construction number. Some manufacturers like Boeing and McDonnell Douglas include the line number, preceded by a /. Thus a Boeing 767, c/n 24542/28 means it has construction number 24542, and that it is the 28th B767 off the production line. Construction numbers for each manufacturer are usually unique.

### 2.Engines
- Number and type (model and mark) of engines.

## Feature Category Fatalities

### 7. Crew
- Exact number of flight- and cabincrew members aboard the aircraft at the time of departure, and number of passengers fatally injured as a direct result of the accident. An injury is classified as fatal if death results from the injury within 30 days from the date of the accident (ICAO) Deadheading crewmembers are judged 'passengers'.

### 14. TotalFatalities

### 21. Passengers
- Number of passengers aboard the aircraft at the time of departure, and number of passengers fatally injured as a direct result of the accident. 
An injury is classified as fatal if death results from the injury within 30 days from the date of the accident (ICAO)
Total:	Number of occupants (crew + passengers) aboard the aircraft at the time of the accident, and number of occupants fatally injured as a direct result of the accident. An injury is classified as fatal if death results from the injury within 30 days from the date of the accident (ICAO).

### 11. GroundCasualities
- Number of fatalities on the ground as a direct result of the occurrence. Ground casualties exclude fatalities as a result of an airplane collision on the ground.
See also: Collision casualties

### 36. CollisionCasualties
- Number of fatalities aboard other aircraft involved in collision accidents.

## Feature Category Crash Details

### 3. CrashSiteElevation

### 20. Phase
- Phase of flight. The flight phases are in accordance with the broad phases defined by the CAST/ICAO Common Taxonomy Team (CICTT), as laid down in the Phase of Flight Definitions document (October, 2002)

### 4. Duration - Same as Total airframe hours?

### 5. Narrative
- Description of the occurrence.

### 25. Date
- Date of occurrence (local time), format DD MMM YYYY. DD or MMM becomes XX or XXX if the exact day or month of an occurrence is unknown.

### 29. DepartureAirport
- Last airport of departure before the accident (between brackets if known the IATA airport code).

### 23. DestinationAirport
- Scheduled destination airport. In case of diversions, the intended destination airport is given (between brackets if known the IATA airport code).

### 17. AirplaneDamage
- Describes the amount of damage to the airplane as a result of the occurrence. Possible values are: Written off (See also: Definitions), Substantial, Minor, None, and Unknown.

### 26. Time
- Time of the accident – local time.

### 35. AirplaneFate
- Describes the amount of damage to the airplane as a result of the occurrence. Possible values are: Written off (See also: Definitions), Substantial, Minor, None, and Unknown.

### 15. TotalAirFrameHrs - What is this?
- Total airframe hours at the time of the accident.

### 27. Cycles - What category to put this ?
- Total number of take-offs and landings at the time of the accident.

### 8. Location
- Location of the incident

## Feature Category - Investigation results

### 28. DownloadReport - What is this?

### 30. Issued -When was report issued?

### 18. Released

### 12. Status
- Status of the information. Final means that the official final investigation report was used to compile the accident description. Preliminary- Official means that the official preliminary investigation report was used and Preliminary means press information and other unofficial information was used.

### 34. DurationOfInvestigation

### 9. InvestigatingAgency

In [ ]:
data['Date'] = [d.split()[-1] for d in data['Date']]

In [ ]:
data = data[data['Date'] != 'unk']

In [ ]:
data = data[data['Date'] != 'unk.']

In [ ]:
data = data[data['Date'] != '195.']

In [ ]:
data = data[data['Date'] != '197x']

In [ ]:
import re

In [ ]:
test  = 'ABs9'
print(re.match("[0-9]", test))

In [ ]:
import re

data['Date'] = [0 if (re.match("[0-9]", d)) == None else int(d) for d in data['Date']]

In [ ]:
# data = data[data['Date'] > 1980]

In [ ]:
data.shape

In [ ]:
checknullcount(data)

In [ ]:
data['Nature'].value_counts()